START_HTML = """
<html>

<head>
  <link rel="stylesheet" href="css/reveal.css">
  <link rel="stylesheet" href="css/theme/white.css">
</head>

<body>
  <div class="reveal">
    <div class="slides">
"""


def slide_html(text, img_url):
    return f"""
            <section data-background-image="{img_url}>"
            <p id="slide-title">{text}</p>
            </section>
            """


END_HTML = """
            </div>
        </div>
        <script src="js/reveal.js"></script>
        <script>
            Reveal.initialize();
        </script>
        </body>

        </html>
"""


test_deck = {
    "slides": [
        {
            "title": "Hello!",
            "img_url": "https://images.unsplash.com/photo-1562184760-a11b3cf7c169?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2100&q=80",
        },
        {
            "title": "This is my deck!",
            "img_url": "https://images.unsplash.com/photo-1562184724-0b0833e5ba27?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3766&q=80",
        },
        {
            "title": "And we're done!",
            "img_url": "https://images.unsplash.com/photo-1562184647-979b4a9f0b23?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3900&q=80",
        },
    ]
}

words = {
    "adjectives": [
        "24/7",
        "24/365",
        "accurate",
        "adaptive",
        "agile",
        "alternative",
        "an expanded array of",
        "B2B",
        "B2C",
        "backend",
        "backward-compatible",
        "best-of-breed",
        "bleeding-edge",
        "bricks-and-clicks",
        "business",
        "clicks-and-mortar",
        "client-based",
        "client-centered",
        "client-centric",
        "client-focused",
        "cloud-based",
        "cloud-centric",
        "cloudified",
        "collaborative",
        "compelling",
        "competitive",
        "cooperative",
        "corporate",
        "cost effective",
        "covalent",
        "cross functional",
        "cross-media",
        "cross-platform",
        "cross-unit",
        "customer directed",
        "customized",
        "cutting-edge",
        "distinctive",
        "distributed",
        "diverse",
        "dynamic",
        "e-business",
        "economically sound",
        "effective",
        "efficient",
        "elastic",
        "emerging",
        "empowered",
        "enabled",
        "end-to-end",
        "enterprise",
        "enterprise-wide",
        "equity invested",
        "error-free",
        "ethical",
        "excellent",
        "exceptional",
        "extensible",
        "extensive",
        "flexible",
        "focused",
        "frictionless",
        "front-end",
        "fully researched",
        "fully tested",
        "functional",
        "functionalized",
        "fungible",
        "future-proof",
        "global",
        "go forward",
        "goal-oriented",
        "granular",
        "high standards in",
        "high-payoff",
        "hyperscale",
        "high-quality",
        "highly efficient",
        "holistic",
        "impactful",
        "inexpensive",
        "innovative",
        "installed base",
        "integrated",
        "interactive",
        "interdependent",
        "intermandated",
        "interoperable",
        "intuitive",
        "just in time",
        "leading-edge",
        "leveraged",
        "long-term high-impact",
        "low-risk high-yield",
        "magnetic",
        "maintainable",
        "market positioning",
        "market-driven",
        "mission-critical",
        "multidisciplinary",
        "multifunctional",
        "multimedia based",
        "next-generation",
        "on-demand",
        "one-to-one",
        "open-source",
        "optimal",
        "orthogonal",
        "out-of-the-box",
        "pandemic",
        "parallel",
        "performance based",
        "plug-and-play",
        "premier",
        "premium",
        "principle-centered",
        "proactive",
        "process-centric",
        "professional",
        "progressive",
        "prospective",
        "quality",
        "real-time",
        "reliable",
        "resource-sucking",
        "resource-maximizing",
        "resource-leveling",
        "revolutionary",
        "robust",
        "scalable",
        "seamless",
        "stand-alone",
        "standardized",
        "standards compliant",
        "state of the art",
        "sticky",
        "strategic",
        "superior",
        "sustainable",
        "synergistic",
        "tactical",
        "team building",
        "team driven",
        "technically sound",
        "timely",
        "top-line",
        "transparent",
        "turnkey",
        "ubiquitous",
        "unique",
        "user-centric",
        "user friendly",
        "value-added",
        "vertical",
        "viral",
        "virtual",
        "visionary",
        "web-enabled",
        "wireless",
        "world-class",
        "worldwide",
    ],
    "verbs": [
        "actualize",
        "administrate",
        "aggregate",
        "architect",
        "benchmark",
        "brand",
        "build",
        "cloudify",
        "communicate",
        "conceptualize",
        "coordinate",
        "create",
        "cultivate",
        "customize",
        "deliver",
        "deploy",
        "develop",
        "dinintermediate disseminate",
        "drive",
        "embrace",
        "e-enable",
        "empower",
        "enable",
        "engage",
        "engineer",
        "enhance",
        "envisioneer",
        "evisculate",
        "evolve",
        "expedite",
        "exploit",
        "extend",
        "fabricate",
        "facilitate",
        "fashion",
        "formulate",
        "foster",
        "generate",
        "grow",
        "harness",
        "impact",
        "implement",
        "incentivize",
        "incept",
        "incubate",
        "initiate",
        "innovate",
        "integrate",
        "iterate",
        "leverage existing",
        "leverage other's",
        "maintain",
        "matrix",
        "maximize",
        "mesh",
        "monetize",
        "morph",
        "myocardinate",
        "negotiate",
        "network",
        "optimize",
        "onboard",
        "orchestrate",
        "parallel task",
        "plagiarize",
        "pontificate",
        "predominate",
        "procrastinate",
        "productivate",
        "productize",
        "promote",
        "provide access to",
        "pursue",
        "recaptiualize",
        "reconceptualize",
        "redefine",
        "re-engineer",
        "reintermediate",
        "reinvent",
        "repurpose",
        "restore",
        "revolutionize",
        "right-shore",
        "scale",
        "seize",
        "simplify",
        "strategize",
        "streamline",
        "supply",
        "syndicate",
        "synergize",
        "synthesize",
        "target",
        "transform",
        "transition",
        "underwhelm",
        "unleash",
        "utilize",
        "visualize",
        "whiteboard",
    ],
    "nouns": [
        "action items",
        "adoption",
        "alignments",
        "applications",
        "architectures",
        "bandwidth",
        "benefits",
        "best practices",
        "catalysts for change",
        "channels",
        "clouds",
        "collaboration and idea-sharing",
        "communities",
        "content",
        "convergence",
        "core competencies",
        "customer service",
        "data",
        "deliverables",
        "e-business",
        "e-commerce",
        "e-markets",
        "e-tailers",
        "e-services",
        "experiences",
        "expertise",
        "functionalities",
        "fungibility",
        "growth strategies",
        "human capital",
        "ideas",
        "imperatives",
        "infomediaries",
        "information",
        "infrastructures",
        "initiatives",
        "innovation",
        "intellectual capital",
        "interfaces",
        "internal or organic sources",
        "leadership",
        "leadership skills",
        "manufactured products",
        "markets",
        "materials",
        "meta-services",
        "methodologies",
        "methods of empowerment",
        "metrics",
        "mindshare",
        "models",
        "networks",
        "niches",
        "niche markets",
        "nosql",
        "opportunities",
        "outside the box thinking",
        "outsourcing",
        "paradigms",
        "partnerships",
        "platforms",
        "portals",
        "potentialities",
        "process improvements",
        "processes",
        "products",
        "quality vectors",
        "relationships",
        "resources",
        "results",
        "ROI",
        "scenarios",
        "schemas",
        "scrums",
        "services",
        "solutions",
        "sources",
        "sprints",
        "strategic theme areas",
        "storage",
        "supply chains",
        "synergy",
        "systems",
        "technologies",
        "technology",
        "testing procedures",
        "total linkage",
        "users",
        "value",
        "vortals",
        "web-readiness",
        "web services",
        "wins",
        "virtualization",
    ],
}

